apiVersion: v1
kind: Service
metadata:
  name: devops-java-app-service
  labels:
    app: devops-java-app
spec:
  type: ClusterIP
  selector:
    app: devops-java-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
